#!/bin/sh
echo "Running postrm step..."

## Menu updating
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
    update-menus
fi
## Update mime database
if [ "$1" = "configure" ] && [ -x "`which update-mime-database 2>/dev/null`" ]; then
   update-mime-database /usr/share/mime
fi
## Update mime icon
if [ "$1" = "configure" ] && [ -x "`which update-icon-caches 2>/dev/null`" ]; then
   update-icon-caches /usr/share/icons/hicolor
fi
echo "Done"
